
## @param extraSecrets Optionally specify extra secrets to be created by the chart.
## This can be useful when combined with load_definitions to automatically create the secret containing the definitions to be loaded.
## Example:
## extraSecrets:
##   load-definition:
##     load_definition.json: |
##       {
##         ...
##       }
##
extraSecrets:
  rabbitmq-load-definition:
    load_definition.json: |
      {
        "vhosts": [
          {
            "limits": [],
            "metadata": {
              "description": "Default virtual host",
              "tags": []
            },
            "name": "/"
          }
        ],
        "permissions": [
          {
            "configure": ".*",
            "read": ".*",
            "user": "{{ .Values.auth.username }}",
            "vhost": "/",
            "write": ".*"
          }
        ],
        "policies": [
          {
            "name": "ha-all",
            "pattern": ".*",
            "vhost": "/",
            "definition": {
              "ha-mode": "all",
              "ha-sync-mode": "automatic",
              "ha-sync-batch-size": 1
            }
          }
        ],
        "users":[
            {
                "name": "{{ .Values.auth.username }}",
                "password": "{{ .Values.auth.password }}",
                "tags": "management,policymaker,monitoring,administrator"
            }
        ]
      }


loadDefinition:
  enabled: true
  existingSecret: rabbitmq-load-definition

extraConfiguration: |-
  load_definitions = /app/load_definition.json
