## Installation
# kubectl create -f https://download.elastic.co/downloads/eck/2.1.0/crds.yaml
# kubectl apply -f https://download.elastic.co/downloads/eck/2.1.0/operator.yaml
# kubectl apply -f search-elasticsearch.yaml
# For Helm check this: https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-install-helm.html


apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: {{namespace}}
spec:
  version: {{elastic_version}}
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  nodeSets:
  - name: default
    config:
      node.store.allow_mmap: false
    count: 3
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: {{elastic_persistence_size}}